name: Story
description: Feature or user-facing capability
labels: ["story"]

body:
  - type: textarea
    id: context
    attributes:
      label: Context
  - type: textarea
    id: goal
    attributes:
      label: Goal
  - type: textarea
    id: scope
    attributes:
      label: Scope
  - type: textarea
    id: acceptance
    attributes:
      label: Acceptance Criteria
